<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/10/17 19:37:29

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=creatives',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
