<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/10/17 20:55:01

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=creatives',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
