<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/10/17 21:06:56

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=app2',
  'username' => 'root',
  'password' => 'Sanandreas9',
  'name' => 'doctrine',
)),);
