<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuario', 'doctrine');

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $usuario_codigo
 * @property string $usuario_nombre
 * @property string $usuario_apellido
 * @property string $foto
 * @property date $fechanacimiento
 * @property integer $genero
 * 
 * @method integer getId()               Returns the current record's "id" value
 * @method string  getUsuarioCodigo()    Returns the current record's "usuario_codigo" value
 * @method string  getUsuarioNombre()    Returns the current record's "usuario_nombre" value
 * @method string  getUsuarioApellido()  Returns the current record's "usuario_apellido" value
 * @method string  getFoto()             Returns the current record's "foto" value
 * @method date    getFechanacimiento()  Returns the current record's "fechanacimiento" value
 * @method integer getGenero()           Returns the current record's "genero" value
 * @method Usuario setId()               Sets the current record's "id" value
 * @method Usuario setUsuarioCodigo()    Sets the current record's "usuario_codigo" value
 * @method Usuario setUsuarioNombre()    Sets the current record's "usuario_nombre" value
 * @method Usuario setUsuarioApellido()  Sets the current record's "usuario_apellido" value
 * @method Usuario setFoto()             Sets the current record's "foto" value
 * @method Usuario setFechanacimiento()  Sets the current record's "fechanacimiento" value
 * @method Usuario setGenero()           Sets the current record's "genero" value
 * 
 * @package    creatives
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('usuario_codigo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('usuario_nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('usuario_apellido', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('foto', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('fechanacimiento', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('genero', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}